### ISSUE TITLE
Errors not colored

### ISSUE THREAD

**Issue by JoshDavid** [abrudz/dracula#1]
Seems like the Dracula spec allows for errors to be red (#FF5555). The RGB equivalent is (255, 85, 85).
https://spec.draculatheme.com/#Error

Currently errors are just in white. Was this left out by design? I think it's nice for spotting things like mismatched parentheses in code.

**Comment by abrudz** [comment]
I chose to mark them as [Invalid](https://spec.draculatheme.com/#Invalid) instead of Error because this will also reveal invalid invisible characters like non-breaking spaces and null characters.

You may need to deselect "Single Background" for this theme to work as intended:
![image](https://user-images.githubusercontent.com/10961427/113544957-2ff99c80-95e1-11eb-807a-84b7c46a057d.png)
